###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
services:
  myapp-mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: myapp-mailhog
    ports:
      - "8125:8025"

  myapp-mysql:
    image: 'mysql:8.0'
    container_name: myapp-mysql
    working_dir: /var/www/myapp
    volumes:
        - ../mysql:/var/lib/mysql
        - ../mysql-files:/var/lib/mysql-files
        - ../cakephp:/var/www/myapp
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "8106:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - myapp-mysql
    environment:
      PMA_HOST: myapp-mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"

  myapp-nginx:
    image: 'nginx:alpine'
    container_name: myapp-nginx
    read_only: false
    working_dir: /var/www/myapp
    volumes:
        - ../cakephp:/var/www/myapp:rw
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8180:80"
    links:
     - myapp-php-fpm

  myapp-php-fpm:
    build: ./php-fpm
    container_name: myapp-php-fpm
    working_dir: /var/www/myapp
    volumes:
      - ../cakephp:/var/www/myapp:cached
      - ./php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    links:
      - myapp-mailhog
      - myapp-mysql
